name: Build and push server image to AWS ECR
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'feature/deployment'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest-manual'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      # Step 1: Checkout your repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI and Docker
      - name: Install AWS CLI
        run: |
          sudo apt-get update && \
          sudo apt-get install -y awscli

      # Step 3: Confirm AWS CLI is installed (Optional verification step)
      - name: Verify AWS CLI Installation
        run: aws --version

      - name: Authenticate AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID \
          && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY \
          && aws configure set region $AWS_REGION

        # Step 4: Login to AWS ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

        # Step 5: Build and push Docker image
      - name: Build and push Docker image
        run: |
          cd ./forge # Navigate to context
          echo "Building Docker image..."
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ inputs.ECR_REPO }}:${{ inputs.tag }} -t ${{ secrets.ECR_REGISTRY }}/${{ inputs.ECR_REPO }}:latest .
          echo "Pushing Docker image to Amazon ECR..."
          docker push ${{ secrets.ECR_REGISTRY }}/${{ inputs.ECR_REPO }}:${{ inputs.tag }} && docker push ${{ secrets.ECR_REGISTRY }}/${{ inputs.ECR_REPO }}:latest

      - name: Complete Build Process
        run: echo "🚀 Success"