name: Build and push server image to AWS ECR
run-name: Build and deploy server image 🚀
on:
  push:
    branches:
      - 'feature/deployment'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest-manual'

jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Assume pipeline role
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: 'sts.amazonaws.com'
          role-to-assume: ${{ secrets.PIPELINE_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Confirm AWS Role assume
      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity

        # Step 4: Login to AWS ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

        # Step 5: Build and push Docker image
      - name: Build and push Docker image
        run: |
          cd ./forge # Navigate to context
          echo "Building Docker image..."
          docker build --target server -f .docker/Dockerfile -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO }}:latest .
          echo "Pushing Docker image to Amazon ECR..."
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO }}:latest

      - name: Complete Build Process
        run: echo "🚀 Success"